# Server listener configuration
server:
  host: "192.168.1.140"
  port: "8080"

# Database configuration
database:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "petapi"
  password: "petapi2020"
  name: "petapi"
